version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Install dep
          command: go mod download
      - run:
          name: Build
          command: go build